sonar.projectKey=accounting-service
sonar.projectName=Accounting Service
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_adf296f36a190ba6772378d38b5b3269d3eca388

